### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dbr** [themoritz/plotters-imgui#1]
I was planning on implementing something similar in the next month or so, and having this as a starting point is much appreciated!

However without a license it's a bit tricky to confidently work on this - would you mind adding a license to the repo? Given that imgui/imgui-rs/plotters are all MIT licensed, it's probably not a bad choice :sweat_smile:

**Comment by themoritz** [comment]
Thanks for pointing this out, I just added an MIT license. :)
